stages: [deploy]

deploy_ftp:
  stage: deploy
  image: alpine:3.20
  before_script:
    - apk add --no-cache lftp
  script: |
    lftp -u "$FTP_USER","$FTP_PASS" ftp://$FTP_HOST:$FTP_PORT -e "
      set ftp:passive-mode yes;
      mirror -R --parallel=4 --only-newer --delete \
        --exclude-glob storage/** \
        --exclude-glob uploads/** \
        ./ ${REMOTE_DIR};
      bye"
  only:
    - main
