stages:
  - build
  - deploy

# Build stage (optional - for Laravel optimizations)
build:
  stage: build
  image: php:8.2-cli
  before_script:
    - apt-get update && apt-get install -y git unzip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  script:
    - composer install --optimize-autoloader --no-dev
    - php artisan config:cache || echo "Config cache failed, continuing..."
    - php artisan route:cache
    - php artisan view:cache || echo "View cache failed, continuing..."
  artifacts:
    paths:
      - vendor/
      - bootstrap/cache/
    expire_in: 1 hour
  only:
    - main

# Deploy stage
deploy_production:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache lftp
  script:
    - lftp -c "
        set ftp:ssl-allow no;
        set ftp:passive-mode no;  
        set net:timeout 30;
        set net:max-retries 5;
        open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST $FTP_PORT;
        lcd .;
        cd $FTP_REMOTE_PATH;
        mirror -Rev 
          --exclude-glob=.git* 
          --exclude-glob=.env* 
          --exclude-glob=node_modules* 
          --exclude-glob=tests* 
          --exclude-glob=storage/logs/* 
          --exclude-glob=storage/debugbar/* 
          --exclude-glob=.vscode*
          --delete 
          . .;
        quit"
  dependencies:
    - build
  only:
    - main